### ISSUE TITLE
Ensure QGIS opens maximized on starting up

### ISSUE THREAD

**Issue by batpad** [2i2c-org/nasa-qgis-image#7]
The QGIS app should open full-screen and not require the user to resize the window.

**Comment by batpad** [comment]
To add some colour here:

With https://github.com/2i2c-org/nasa-qgis-image/pull/4, QGIS will now automatically start when the Desktop session is started. The problem is that the window that QGIS starts in covers only a small part of the screen, and we want it to start full-screen.

### Steps to Reproduce:

 - Build and run image following docs in README
 - Open URL and navigate to Desktop in Jupyter Lab
 - You should see an Ubuntu desktop and QGIS starting up

Expected behaviour:

 - QGIS should open full-screen / maximized

Actual behaviour:

 - QGIS opens in a small window and the user needs to click maximize to maximize the window.

I was looking for a flag we could add to the qgis start command here: https://github.com/2i2c-org/nasa-qgis-image/blob/main/qgis.desktop#L8 - some programs accept a `--maximize` flag or so, but this did not seem to work and looking at `qgis --help` did not seem to have anything to force opening maximized.

I think there's two possible routes here:

 - Look if we can specify this in user profile configuration or so in QGIS to ensure it opens full-screen
 - Look if we can modify default window size settings in Ubuntu to get programs to open in full-screen by default

Just putting this out there because my initial naive attempts don't seem to work, so seeing if someone has a good idea here before diving deeper.

cc @geohacker @Rub21

**Comment by Rub21** [comment]
here a posible solution: https://github.com/2i2c-org/nasa-qgis-image/pull/9
![ss_fixed](https://github.com/2i2c-org/nasa-qgis-image/assets/1152236/238355b8-0b98-4700-b32f-2228312e5479)
